---
title: "Checklist and tips for publication-quality graphics in R"
subtitle: "FANR 6750: Experimental Methods in Forestry and Natural Resources Research"
author: "Fall 2022"
output: 
  rmarkdown::html_vignette:
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{Syllabus}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,warning = FALSE, message = FALSE,
  comment = "#>"
)
```

# Attributes of good figures

Below is a list of considerations for making high-quality figures for publications. This is 

- 

- Do you axes start and stop at reasonable values?

- Do your axis titles clearly indicate what variables are being shown? Do they include units? 

- Are your axis labels, axis titles, and text annotations appropriately sized? 

- If your figure includes different colors, shapes, or sizes, do these attributes communicate properties of the data? 

- If your figure includes different colors, shapes, or sizes, do have a legend to show what values are represented by these attributes? 

- Are color palettes colorblind-friendly? 

- Do you have grid lines? If so, do they show relevant information needed to interpret the figure? 

- Did you use a 3D pie chart? 

# Saving figures for publication

# Additional resources

[Fundamentals of Data Visualization](https://clauswilke.com/dataviz/), by Claus Wilke. A comprehensive book on data visualization, with lots of R code

