---
title: "Schedule (subject to change)"
subtitle: "FANR 6750: Experimental Methods in Forestry and Natural Resources Research"
author: "Fall 2022"
output: 
  rmarkdown::html_vignette:
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{Schedule}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE, warning = FALSE, message = FALSE,
  comment = "#>"
)

source(here::here("R/MWF.R"))
```


```{r schedule, echo = FALSE}
library(kableExtra)

schedule <- data.frame(WK = c("1", "", "", 
                              "2", "", "", "",
                              "3", "", "", "", 
                              "4", "", "", "",
                              "5", "", "", "", 
                              "6", "", "", "", 
                              "7", "", "", "", 
                              "8", "", "", "",
                              "9", "", "", "", 
                              "10", "", "", "", 
                              "11", "", "", "", 
                              "12", "", "", "",
                              "13", "", "", "", 
                              "14", "", "", "", 
                              "15", "", "", "", 
                              "16", "", "", "", 
                              "17"),
                       Day = c("W", "F", "", rep(c("M", "W", "F", ""), 15), "M"),
                       Week = MWF(first.day = "2022/08/17", last.day = "2022/12/06"),
                       Lecture = c("Course introduction", "Basic concepts in statistics", "", #1
      "Principles of estimation",  "Principles of estimation", "Intro to statistical modeling", "",#2
      "Intro to statistical modeling", "t-tests and null hypothesis testing", "t-tests and null hypothesis testing", "", #3
      "Labor Day", "t-tests and null hypothesis testing", "Paper discussion: hypothesis testing", "", # 4
      "Randomized ANOVA", "Randomized ANOVA", "Multiple comparisons",   "", #5
       "Statistical power", "Contrasts", "Contrasts", "", #6
      "Transformations", "Nonparametrics", "Nonparametrics", "", #7
       "Random and fixed effects", "Blocking and blocked designs",  "Blocking and blocked designs", "", #8 
      "AB factorial designs", "AB factorial designs", "Paper discussion: Pseudoreplication", "", # 9
       "ABC factorial designs", "Nested designs", "Nested designs", "", #10
          "Split-plot designs", "Split-plot designs", "Fall break", "", #11
      "Repeated measures", "Repeated measures", "Buffer", "",
         "Regression review", "Analysis of covariance", "Analysis of covariance", "", #13
          "Generalized linear models", "Logistic regression", "Poisson regression", "", #14
          "Thanksgiving break", "", "", "", #15
           "GLMMs", "Model selection", "Paper discussion: Model selection",  "", #16
                                   "Course wrap up"),
                       Lab = c("", "", "",
                               "Introduction to R", "", "", "",
                               "Introduction to RMarkdown", "", "", "",
                               "No lab", "", "", "",
                               "R graphics and t-tests", "", "", "",
                               "ANOVA*", "", "", "",
                               "Contrasts and power", "", "", "",
                               "Transformations and nonparametrics*", "", "", "",
                               "Blocking", "", "", "",
                               "Factorial designs*", "", "", "",
                               "Nested designs", "", "", "",
                               "Split-plot designs*", "", "", "",
                               "Repeated measures", "", "", "",
                               "ANCOVA*", "", "", "",
                               "Linear models", "", "", "",
                               "GLMs", "", "", "",
                               # "Model selection", "", "", "",
                               "No lab"),
                       Reading = c("", "Chp. 1", "",
                               "Chp. 2.1-2.3", "", "Chp. 5.2-5.3", "",
                               "", "Chp. 3.1;", "", "",
                               "", "", "Johnson 1999", "",
                               "Chp. 8.1-8.4", "", "Chp. 8.6", "",
                               "Chp. 7.3", "", "", "",
                               "**Exam 1 distributed**", "Chp. 8.5", "", "",
                               "Chp. 8.2; **Exam 1 due**", "Chp. 10.1-10.2", "", "",
                               "Chp. 9.2", "", "Colegrave & Ruxton 2018", "",
                               "", "Chp. 9.1", "", "",
                               "Chp. 11.1-11.3", "", "", "",
                               "", "**Exam 2 distributed**", "", "",
                               "Chp. 6", "Chp. 12; **Exam 2 due**", "", "",
                               "Chp. 13", "", "", "",
                               "", "", "", "",
                               "**Exam 3 distributed**", "", "Tredennick et al. 2021", "",
                               ""))

schedule %>%
  kable("html", col.names = c("Week", "", "Date", "Lecture topic", "Lab topic", "Reading"), align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = TRUE)

```

\* = Graded assignment