---
title: "LECTURE 1: basic concepts in statistics"
subtitle: "FANR 6750 (Experimental design)"
author: "<br/><br/><br/>Fall 2022"
output:
  xaringan::moon_reader:
    css: ["default", "FANR6750.css", "FANR6750-fonts.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, echo = FALSE, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE, fig.align = 'center', warning=FALSE, message=FALSE, fig.retina = 2)
source(here::here("R/zzz.R"))
# library(emo)
# library(gganimate)
```

class: inverse

# outline

<br/>
#### 1) What is statistics?

<br/>  
--

#### 2) Statistics and the scientific method

<br/> 
--

#### 3) Experiments and causal inference

<br/> 

---

# what is statistics?

<br/>
<br/>
> The study of the collection, analysis, interpretation, presentation, and organization of data (Dodge 2006)  

<br/>  
--
<br/>
> The science of learning from data (various)  

---
# why do we need statistics?

### Common tasks  
- Estimate unknown parameters  
<br/>

--
- Test hypotheses  
<br/>

--
- Describe stochastic systems  
<br/>

--
- Make predictions that account for uncertainty  

---
# stats and the scientific method

#### Ways of learnings

--

.pull-left[
**Inductive reasoning**

- Often attributed to Francis Bacon (and others)

- Consistent observations -> general principle

- Problem: "confirmatory" observations can't disprove theory

- Example: I've only seen birds that fly :: all birds can fly
]

--

.pull-right[
**Deductive reasoning**

- Formalized by Karl Popper

- Theory -> predictions -> observations

- Based on *falsification*

- Example: All swans can fly :: penguins are birds :: penguins can fly
]

---
# stats and the scientific method

#### Ways of learnings (real world)

--

1) Pattern identification (i.e., exploratory studies)
- Anecdotes  
- Correlations/visual analysis  
- Exploratory modeling (i.e., fishing)
    
---
# stats and the scientific method

#### Ways of learnings (real world)

1) Pattern identification (i.e., exploratory studies)

2) Hypothesis formation
- Formed from patterns  
- Should focus on mechanisms ("because", "controls", "adapted to") 
- Should be falsifiable  
- Ideally > 1 alternatives  

---
# stats and the scientific method

#### Ways of learnings (real world)

1) Pattern identification (i.e., exploratory studies)

2) Hypothesis formation

3) Predictions
- If the hypothesis is true, what do you expect to see?  
- Focus on things **we can measure**
- More = better
- "associated", "correlated", "greater/less than"

---
# stats and the scientific method

#### Ways of learnings (real world)

1) Pattern identification (i.e., exploratory studies)

2) Hypothesis formation

3) Predictions

4) Data collection
- Can be observational but ideally manipulative experiment  
- Sampling must be *designed* to answer question  

---
# stats and the scientific method

#### Ways of learnings (real world)

1) Pattern identification (i.e., exploratory studies)

2) Hypothesis formation

3) Predictions

4) Data collection

5) Models and testing  
- Model is mathematical abstraction of hypothesis
- Model used to "confront" hypothesis with data (via predictions)
- Draw conclusions: Does data support hypothesis?  

---
# stats and the scientific method

#### Example
1) **Pattern**: Trees at higher elevations are shorter than at low elevations

--

2) **Hypotheses**

--

3) **Predictions**

--

4) **Data collection**<sup>1</sup>


5) **Models**<sup>1</sup>

.footnote[[1] We'll get to these!]

---
class: inverse, middle, center

# causal inference

---
# causal inference

#### Often, we want to know whether $x$ influences $y$

--

- In other words, if we change $x$, will $y$ change also (and by how much)? 

--

- Harder than it seems! Why?

--

- Generally restricted to *manipulative* experiments

--

    + Well-designed experiments ensure that "treatment assignment is independent of the potential outcomes" (Gelman et al. 2021)


---
# looking ahead

<br/>

### **Next time**: Princples of estimation

<br/>

### **Reading**: Quinn chp. 2.1-2.3

